import React from 'react';
import Head from 'next/head';
import TvList from '@/components/TvList';
import Navbar from '@/components/Navbar';

export default function Home() {
  return (
    <div className="bg-[#F8E6BD] w-screen">
      <Head>
        <title>Margaux Didier</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Navbar />
        <TvList listId="8238504" />
      </main>
    </div>
  );
}
